### ISSUE TITLE
添加api域名指向，0.5天

### ISSUE THREAD

**Issue by luckyyang** [rebase-network/synapse-extension#23]
https://synapse-api.rebase.network/ -> 106.13.40.34

使用certbot配置ssl证书：

https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

add-apt-repository ppa:certbot/certbot

apt-get update
apt-get install python-certbot-nginx

ls /etc/letsencrypt/live/
sudo certbot --nginx -d synapse-api.rebase.network/

**Comment by syuukawa** [comment]
尊敬的用户（1e7b62f7ba834a3580e5a029197c41ae），经检测有如下（rebase.network）不符合要求的域名（未备案/未接入）指向了您购买的百度云IP，按照工信部相关规定已对上述域名阻断访问，请您知晓并关注。
