### ISSUE TITLE
Address validation in contact management - 0.5天

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#62]
Hi there,

In the latest version 0.0.13, when adding a new contact, it doesn't do the address validation before adding a new address to the contact list. I think it would be more secure to validate the address string instead of allowing any string to be contact addresses.

<img width="370" alt="Screen Shot 2020-07-28 at 12 34 27 PM" src="https://user-images.githubusercontent.com/1587352/88645360-9a734800-d0f6-11ea-9543-e56106254124.png">

**Comment by luckyyang** [comment]
We will add the validation, thanks for the feedback!

**Comment by luckyyang** [comment]
Validation added:
![](https://user-images.githubusercontent.com/1963646/90596874-849f0180-e222-11ea-8ef8-a401dae071f2.png)
