### ISSUE TITLE
UDTs in expanded panel - 0.5天

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#63]
If you don't mind, could you please explain a bit about the meaning of the links on the left? 
I am wondering if they are the type script hashes. If so, when clicked one of the links, would it be better to pre-fill the UDT form in the UDT management view? I am bit confused when it shows me the empty UDT form after clicking one of the links.

<img width="351" alt="Screen Shot 2020-07-28 at 12 45 57 PM" src="https://user-images.githubusercontent.com/1587352/88646646-dce95480-d0f7-11ea-85a7-2323a328004d.png">

**Comment by luckyyang** [comment]
We will add the explanation and pre-fill feature, thanks!

**Comment by luckyyang** [comment]
![image](https://user-images.githubusercontent.com/1963646/88832617-aa2c8280-d203-11ea-917f-63babe38bb85.png)

**Comment by luckyyang** [comment]
Add a link to explorer: 
`EXPLORER_URL/sudt/:typeHash`
For example:
https://explorer.nervos.org/aggron/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa

**Comment by luckyyang** [comment]
Pre-fill is added:
![image](https://user-images.githubusercontent.com/1963646/90597027-d778b900-e222-11ea-885a-d68137748264.png)
![image](https://user-images.githubusercontent.com/1963646/90597032-da73a980-e222-11ea-813c-1fb500347ea1.png)
