### ISSUE TITLE
UDT management form

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#64]
I am not quite sure how this form works, and how it relates to the other functions. I guess it is something related to [this issue](https://github.com/rebase-network/synapse-extension/issues/63) I just created.
<img width="364" alt="Screen Shot 2020-07-28 at 12 49 24 PM" src="https://user-images.githubusercontent.com/1587352/88647303-787ac500-d0f8-11ea-9b8d-258f84c5d565.png">

**Comment by luckyyang** [comment]
Yes, they are related. Let us figure out a way to make it easy to understand. Or you can advise, thanks.

**Comment by luckyyang** [comment]
This is the image flow to show how it works:
![image](https://user-images.githubusercontent.com/1963646/88832617-aa2c8280-d203-11ea-917f-63babe38bb85.png)

**Comment by luckyyang** [comment]
I did a short explanation during the 2nd review call, you can find the screenshots along with other features here: https://docs.google.com/presentation/d/1nsMUDMQlawz7MWk9A5Sr2WAy3slZEsKA985sE-czVAo/edit?usp=sharing

**Comment by luckyyang** [comment]
This issue is related to #63, we will do it in that issue.
