### ISSUE TITLE
Anypay - Unexpected fees - 1天

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#66]
There is a scenario in which Synapse put together a transaction that offers an unexpected fee amount. For example:

1. Alice got a ACP lock cell having 100 CKB.
2. Alice fills the specify to transfer 61 CKB to Bob in the form.
3. The fee indicated in the forms is 0.0001
4. After the transaction, the ACP cell disappeared, and the transaction leaving 39 CKB for the miner

https://explorer.nervos.org/aggron/transaction/0xc704bff6cf7fab579d442e763f5437dbc520195a80db681515ef1818c015eb97

<img width="350" alt="Screen Shot 2020-07-30 at 2 45 07 PM" src="https://user-images.githubusercontent.com/1587352/88890551-5e65f180-d274-11ea-8861-464521956059.png">

<img width="352" alt="Screen Shot 2020-07-30 at 2 45 26 PM" src="https://user-images.githubusercontent.com/1587352/88890546-5c039780-d274-11ea-8982-874ed809a764.png">

The other issue is the wordings in the input warning:
`the remaining capacity is 61` => `the remaining capacity is 61 CKB`. The amount unit should be based on the currency selected for the transaction. 
`remaining capacity is39` => `remaining capacity is 39 CKB`

Meanwhile, but I don't see there is a way to choose a currency to transfer. Should this currency selection feature be expected in this milestone?

**Comment by luckyyang** [comment]
> After the transaction, the ACP cell disappeared, and the transaction leaving 39 CKB for the miner
Right, it's a bug. we should have a special handling for ACP, cause it's possible to have a 39 CKB cell in output. If it's not ACP, this 39 CKB will be lost

The wordings issue we will fix them.

> Should this currency selection feature be expected in this milestone?
Yes it's in our plan and backlog. We recently are adding mainnet support, probably add them to our todo list after this stage.

**Comment by luckyyang** [comment]
Send sUDT is supported:
![image](https://user-images.githubusercontent.com/1963646/90597211-33dbd880-e223-11ea-987a-13e655962e01.png)
