### ISSUE TITLE
Error attempting to install release 0.1.0 in Chrome

### ISSUE THREAD

**Issue by tspoff** [rebase-network/synapse-extension#76]
Followed the non-developer instructions, error when loading the unpacked directory:
![image](https://user-images.githubusercontent.com/5606917/91074412-1ed7be80-e602-11ea-9d71-ea2287b70e16.png)

**Comment by luckyyang** [comment]
@tspoff Did the installation successfully after this error?

**Comment by luckyyang** [comment]
fixed
