### ISSUE TITLE
Issues in 0.1.0

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#77]
After upgrading to 0.1.0, the synpase dropdown doesn't look right. See the screenshots:

1. It doesn't seem to be compatible the existing wallet data
![Screen Shot 2020-08-26 at 6 16 15 AM](https://user-images.githubusercontent.com/1587352/91233378-a721a500-e763-11ea-957c-6b3f2d84f4ab.png)

2. It doesn't show the existing wallets.
![Screen Shot 2020-08-26 at 6 16 50 AM](https://user-images.githubusercontent.com/1587352/91233416-bb65a200-e763-11ea-8b7e-613b54ae883a.png)

3. Then when clicked the `Show UDT`, it shows up the assets. Also, when the `Show UDT` is clicked, initially it shows `No UDT found` and then shows the assets after a second. I think it shouldn't display `No UDT found` when it is loading the assets. It'd better display a loading indicator when it is loading.

![Screen Shot 2020-08-26 at 6 17 39 AM](https://user-images.githubusercontent.com/1587352/91233474-d9330700-e763-11ea-8f72-855d1175e050.png)

4. When clicked the menu icon, it displays a blank screen.
![Screen Shot 2020-08-26 at 6 19 12 AM](https://user-images.githubusercontent.com/1587352/91233568-10a1b380-e764-11ea-8198-7b42cdb56c13.png)

5. The buttons are better to be aligned at the center.
![Screen Shot 2020-08-26 at 6 25 54 AM](https://user-images.githubusercontent.com/1587352/91234001-00d69f00-e765-11ea-90bf-08b16d99fd69.png)

6. How the local environment should be set up for the local network chosen here?
![Screen Shot 2020-08-26 at 6 27 12 AM](https://user-images.githubusercontent.com/1587352/91234120-311e3d80-e765-11ea-9a48-8371cf4a6851.png)

7. These UI elements should be better aligned
![Screen Shot 2020-08-26 at 6 29 03 AM](https://user-images.githubusercontent.com/1587352/91234255-704c8e80-e765-11ea-9a41-6783a9d77119.png)

8. Should the keystore be better uploaded as file instead of passing in the keystore string? I tried to pass in a keystore as string, but it failed to recognize the keystore even with a correct password.
![Screen Shot 2020-08-26 at 7 01 35 AM](https://user-images.githubusercontent.com/1587352/91236311-2c0fbd00-e76a-11ea-91ac-5e0577115cbd.png)

9. All the forms should have proper validations to make sure the inputs are in the correct format.
![Screen Shot 2020-08-26 at 7 12 35 AM](https://user-images.githubusercontent.com/1587352/91236912-c7556200-e76b-11ea-9d54-edc2c9ba968e.png)

**Comment by luckyyang** [comment]
No. 7 fixed

**Comment by luckyyang** [comment]
1, 2, 4 is due to compatible issue, which we will not consider for current stage.
We will not let the extension break after we release v1.0

**Comment by luckyyang** [comment]
No. 6 fixed, added a link to setting page for managing networks
![image](https://user-images.githubusercontent.com/1963646/93896532-9a24b100-fd23-11ea-9466-9a02bb7a27f7.png)

**Comment by billie66** [comment]
No. 5 fixed

**Comment by billie66** [comment]
The shadow of the right arrow icon is not a circle

<img width="354" alt="Screen Shot 2020-09-23 at 11 30 00 AM" src="https://user-images.githubusercontent.com/102444/93963879-db9f7580-fd90-11ea-8e80-2925f48978b6.png">

**Comment by billie66** [comment]
No. 3 fixed

**Comment by billie66** [comment]
>The shadow of the right arrow icon is not a circle
It was fixed

<img width="356" alt="Screen Shot 2020-09-24 at 10 47 25 AM" src="https://user-images.githubusercontent.com/102444/94095098-909a6680-fe53-11ea-8d96-ce5116ebb407.png">

**Comment by billie66** [comment]
No.8 
<img width="360" alt="Screen Shot 2020-09-24 at 10 21 30 PM" src="https://user-images.githubusercontent.com/102444/94158047-7cd31c80-feb4-11ea-8a41-de7ea2f87857.png">

**Comment by billie66** [comment]
No.9 fixed

<img width="370" alt="Screen Shot 2020-09-25 at 5 18 33 PM" src="https://user-images.githubusercontent.com/102444/94250170-7051d100-ff53-11ea-8274-829fa7ea33b4.png">
