### ISSUE TITLE
Show error code and info when the transaction fails

### ISSUE THREAD

**Issue by duanyytop** [rebase-network/synapse-extension#82]
Please add error code and info when the transaction fails to help developers to find bugs. Thanks

**Comment by luckyyang** [comment]
Thanks for the feedback, we will add it

**Comment by luckyyang** [comment]
https://nervosnetwork.github.io/keypering/#/protocol  keypering 的错误码
https://github.com/nervosnetwork/ckb-system-scripts/wiki/Error-codes ckb 的错误码

**Comment by duanyytop** [comment]
I mean the result of Synapse should be displayed on the chrome notification window.

**Comment by luckyyang** [comment]
I see, thanks for the clarification

**Comment by luckyyang** [comment]
Added
