### ISSUE TITLE
Can't sign transaction on the simplestdapp

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#83]
<img width="1306" alt="Screen Shot 2020-10-18 at 5 38 05 PM" src="https://user-images.githubusercontent.com/1587352/96363752-b07a2d00-1168-11eb-8a19-6227f32b7ccf.png">

There are 4 issues in this workflow I can spot so far.
1. When I am trying to create a cell, after entered the password, the Synpase extension says "Your Tx failed to send".
2. The popup firstly displays this page and then redirect to the password form. It should directly go to the password form.
<img width="472" alt="Screen Shot 2020-10-18 at 5 40 32 PM" src="https://user-images.githubusercontent.com/1587352/96363806-09e25c00-1169-11eb-8318-97e104fa9b33.png">
3. When I resize the popup, the UI is not responsive to the size of the popup window.
<img width="745" alt="Screen Shot 2020-10-18 at 5 41 59 PM" src="https://user-images.githubusercontent.com/1587352/96363836-3bf3be00-1169-11eb-9235-995ccc70bb26.png">
4. The underline of the network dropdown doesn't seem to be well aligned.
<img width="369" alt="Screen Shot 2020-10-18 at 5 44 21 PM" src="https://user-images.githubusercontent.com/1587352/96363910-c3d9c800-1169-11eb-9b91-8aa2270fa67e.png">

**Comment by luckyyang** [comment]
Responsive popup will be like this and will be release soon:
![image](https://user-images.githubusercontent.com/1963646/96563724-df250e80-12f4-11eb-8b49-d3d66c2650d2.png)

**Comment by luckyyang** [comment]
> 1. When I am trying to create a cell, after entered the password, the Synpase extension says "Your Tx failed to send".

Fixed.
This is due to the rpc node did not work, I replaced it with another rpc node.

**Comment by luckyyang** [comment]
> 2. The popup firstly displays this page and then redirect to the password form. It should directly go to the password form.

Fixed.

**Comment by luckyyang** [comment]
> 4. The underline of the network dropdown doesn't seem to be well aligned.

Fixed

**Comment by luckyyang** [comment]
@katat These fixes are included in the new release: https://github.com/rebase-network/synapse-extension/releases/tag/v0.1.3
