### ISSUE TITLE
Outdated AnyoneCanPay / SUDT script

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#88]
The official ACP / SUDT scripts have been upgraded, I think synapse has to be updated according as well. Otherwise, the other wallets, such as Neuron can't make transfers to the ACP addresses managed by synpase.

For the updated scripts, please refer to 

 - ACP: https://github.com/nervosnetwork/rfcs/blob/de480cb9af9c728f826bd13d0cf008ac9a3dc72e/rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md#anyone_can_pay
 - UDT: https://github.com/nervosnetwork/rfcs/blob/de480cb9af9c728f826bd13d0cf008ac9a3dc72e/rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md#anyone_can_pay

**Comment by luckyyang** [comment]
We only need to update anypay lock info for testnet. Updated and tested pass:
https://explorer.nervos.org/aggron/transaction/0x636bb877d818a00bf7126a29248b5dddb04fe2bd04472c564086f5ead6eabd36

**Comment by katat** [comment]
@luckyyang 
Please update the UDT following this PR https://github.com/nervosnetwork/rfcs/pull/214/files

**Comment by luckyyang** [comment]
UDT info updated
