### ISSUE TITLE
Send form

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#91]
![Screen Shot 2021-01-11 at 4 14 45 PM](https://user-images.githubusercontent.com/1587352/104158377-359f7600-5428-11eb-86da-d0af5f78b384.png)

 - should disble the send form
 - should show the pending transaction hash, so the users can lookup on explorer.

**Comment by katat** [comment]
Meanwhile, I noticed the transaction isn't broadcast to the network even I clicked the button and the notification on the top is displayed.

The transaction I attempt to make is make a transfer from an ACP address to another ACP address.

**Comment by luckyyang** [comment]
> I noticed the transaction isn't broadcast to the network

I found this issue is due to you enter incorrect password and we do not give a proper prompt on UI, I added the prompt. I am able to send the transaction from anypay to anypay now:
https://explorer.nervos.org/aggron/transaction/0x4000c2483374e37ee499181edb30a84caacb9f444f9acd92742b4db5e5db1508

**Comment by luckyyang** [comment]
> should show the pending transaction hash, so the users can lookup on explorer.

Yes, there is, after the tx is sent.
![image](https://user-images.githubusercontent.com/1963646/104286282-c8571800-54ef-11eb-892a-70c574ea988a.png)

**Comment by luckyyang** [comment]
> should disble the send form
Added

**Comment by katat** [comment]
![Screen Shot 2021-01-28 at 4 40 39 PM](https://user-images.githubusercontent.com/1587352/106114034-14f65080-618a-11eb-9252-e41a5ed16a5a.png)

The address field is invalid, but it still allows sending the transaction.
