### ISSUE TITLE
Edit data in simplestdapp

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#92]
When I created a cell with data, and then try to update it, the outputsData in the transaction review panel of the signing popup is not consistent with what I try to update.

![Screen Shot 2021-01-11 at 4 44 09 PM](https://user-images.githubusercontent.com/1587352/104160708-85803c00-542c-11eb-93a5-d8d2061d6ef2.png)

**Comment by luckyyang** [comment]
I just tested it locally, seems no issue for me:
![image](https://user-images.githubusercontent.com/1963646/104303152-af0c9680-5504-11eb-8a00-611944b05534.png)

**Comment by luckyyang** [comment]
@katat Which synapse version did you test with? I can not reproduce this issue.

**Comment by katat** [comment]
I used the latest version of synapse from the github repo.
This issue occurs when trying to update the cell's data.

**Comment by luckyyang** [comment]
Weird, the screenshot I took is **updating** the cell and successfully

**Comment by luckyyang** [comment]
It's the result:
![image](https://user-images.githubusercontent.com/1963646/104316848-0a944f80-5518-11eb-8971-f77f539ce5a7.png)

**Comment by luckyyang** [comment]
@katat Did you run simplestdapp locally with the code https://github.com/rebase-network/simplestdapp ?

**Comment by katat** [comment]
Yes, that is the one I run.

**Comment by luckyyang** [comment]
I found the root cause, it's due to the extra space, will fix it:
![image](https://user-images.githubusercontent.com/1963646/104408794-d19fbd80-559f-11eb-9049-5f6df7e089b9.png)

**Comment by luckyyang** [comment]
Fixed, you can try with latest code of https://github.com/rebase-network/simplestdapp
