### ISSUE TITLE
udt should be editable

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#93]
The `udt` item should be editable
![Screen Shot 2021-01-14 at 4 00 01 PM](https://user-images.githubusercontent.com/1587352/104561120-d6d53900-5681-11eb-8707-28e79d0b3319.png)
 

When clicking the `udt` item in the main panel, it should go to the edit form, instead of an add form.
![Screen Shot 2021-01-14 at 3 59 05 PM](https://user-images.githubusercontent.com/1587352/104560993-a7bec780-5681-11eb-8a0b-18e5ddeefddb.png)

**Comment by luckyyang** [comment]
Now support edit udt info
