### ISSUE TITLE
tx hash should be displayed even it is pending

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#94]
![Screen Shot 2021-01-14 at 4 07 38 PM](https://user-images.githubusercontent.com/1587352/104562019-bc4f8f80-5682-11eb-9ccf-0039865025ac.png)

**Comment by luckyyang** [comment]
Is it always unable to display? Did the transaction send successfully?
Just tested, it's able to display on my side.

**Comment by luckyyang** [comment]
Changed the way to generate tx hash off chain and tested ok. Could you try again? Thanks @katat
