### ISSUE TITLE
Incorrect udt amount

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#95]
There was a transfer to the synapse wallet address with amount 100 in decimal 1 configured. However, the UI displays 1 UDT, I think instead it should display 10?

![Screen Shot 2021-01-14 at 4 15 12 PM](https://user-images.githubusercontent.com/1587352/104562880-e48bbe00-5683-11eb-82a5-bd9a5f4743fc.png)

![Screen Shot 2021-01-14 at 4 17 39 PM](https://user-images.githubusercontent.com/1587352/104562966-06854080-5684-11eb-9633-a49cfb21028a.png)

tx: https://explorer.nervos.org/aggron/transaction/0x49e027e558a620272655bfb2aff7be7e948b37a59df099178ab33a8dc73ca5a6

**Comment by luckyyang** [comment]
Fixed

**Comment by katat** [comment]
I tried to send 0.1 SUDT but somehow synapse shows its transaction with 21 SUDT sent.

![Screen Shot 2021-01-28 at 4 54 27 PM](https://user-images.githubusercontent.com/1587352/106113631-a87b5180-6189-11eb-87e1-3daf64cbacc4.png)

![Screen Shot 2021-01-28 at 4 54 53 PM](https://user-images.githubusercontent.com/1587352/106113639-ac0ed880-6189-11eb-97cb-971f5e64f9c7.png)

https://explorer.nervos.org/aggron/transaction/0x91823ef6c88dbc0ce02435f54c3ec6e082f971b44991fd678d2ff76416469a98

**Comment by luckyyang** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1963646/107942453-3a76bd00-6fc6-11eb-9933-30260524b732.png)
