### ISSUE TITLE
Support ACP short address

### ISSUE THREAD

**Issue by katat** [rebase-network/synapse-extension#96]
The official now recommends using the short address for the ACP locks. See https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md#short-payload-format

Otherwise, the ACP addresses in Synapse will be inconsistent with the ones in explorer and it can't transfer access to the other wallets such as Neuron.

**Comment by luckyyang** [comment]
Added
